config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end

  #get '/articles', to: 'articles#index'
  # Users 
  get '/signup', to: 'users#new'
  get '/user/articles', to: 'articles#user_index'
  resources :users

  post '/toggle_follow', to: 'articles#toggle_follow'
  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}

end

app/models/comment.rb
class Comment < ApplicationRecord
  includes Visible
  belongs_to :article
  belongs_to :user
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: {in: VALID_STATUSES}
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/follower.rb
class Follower < ApplicationRecord
  validates :user_id, presence: true
  validates :following, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  include Visible
  has_many :articles
  has_secure_password
  before_save { self.email = email.downcase }
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  helper_method :logged_in?, :current_user

  def logged_in?
    !current_user.nil?
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :logged_in_user

  def home
  end

  def new
    @article = current_user.articles.new
  end

  def index
    @articles = Article.all.select { |a| a.status == 'public' }
  end

  def user_index
    @articles = Article.all
    @articles = @articles.select { |a| a.user_id == @current_user.id }
    render 'user_index'
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      flash[:success] = 'Article has been created!'
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])

    if @article.update(article_params)
      flash[:success] = 'Article updated'
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = current_user.articles.find(params[:id])
    if @article
      @article.destroy
      flash[:success] = 'Article has been deleted'
    else
      flash[:alert] = 'Error'
    end
    redirect_to root_path
  end

  def show
    begin
      @article = Article.find(params[:id]) # Instance variable
      if @article.user_id == @current_user.id
        @article
      else
        @visitor = true
      end
    rescue
      flash[:alert] = 'This article doesn\'t exist.'
      redirect_to articles_path
    end
  end

  def toggle_follow
    if Follower.exists?(user_id: params[:current_user], following: params[:author])
      follow = Follower.where(user_id: params[:current_user], following: params[:author])
      follow = follow.first # first element, bc .where returns an array(in this case of just one element)
      Follower.destroy(follow.id)
    else
      follow = Follower.new(user_id: params[:current_user], following: params[:author])
      follow.save
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end

  private 
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper_method :current_user, :log_out, :current_user?, :log_in
  # Render the new.html.erb template (The login form)
  def new
  end

  # Don't render a template, just create the session
  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = 'Welcome.'
      redirect_back_or articles_path
    else
      flash.now[:danger] = 'Invalid email/password combination.'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user) 
    user == current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    puts "USEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEER #{@user.to_s}"
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to the app!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def get_author(user_id)
    User.find(user_id)
  end

  def following?(author)
    following = Follower.where(user_id: current_user.id).to_a
    following = following.map { |f| f.following }
    puts "Following to: #{following}, Author:#{author}"
    following.include?(author)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <div class="form-group">
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'form-control'%>
    </div>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <div class="form-group">
      <%= form.label :body%><br>
      <%= form.text_area :body, {class: 'form-control'}%><br>
    </div>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :status %> <br>
    <%= form.select  :status,['public', 'private', 'archived'],{},{selected: 'public', class:'form-select'} %>
  </div>
<br>
  <div class="form-group">
    <%= form.submit class:'btn btn-success'%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', article: @article %>
</div>

app/views/articles/index.html.erb
<div class="row">
  <h1>Articles</h1>
</div>
<br>
<h1 class="text-warning">Hi! this blog has <em><%= Article.public_count %> public </em> articles and counting!</h1>
<br>
<div class="row">
  <% @articles.each do |a|%>
    <div class="col col-lg-4">
      <div class="card border-primary mb-3 mw-20rem">
        <div class="card-header">
          <svg xmlns="http://www.w3.org/2000/svg" class="avatar" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
            <path fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
          </svg>
          <%= get_author(a.user_id).name%>
          <% case a.status %>
          <% when 'public' %>
          <span class="badge bg-warning" >Public</span>
          <% when 'private' %>
          <span class="badge bg-dark" >Private</span>
          <% when 'archived' %>
          <span class="badge bg-danger" >Archived</span>
        <% end%>
      </div>
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to a.title, a %>
        </h4>
        <p class="card-text"><%= a.body %></p>
      </div>
    </div>
  </div>
<%end%>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="content">
  <div class="card border-primary mb-3" >
    <div class="card-header">
      <svg xmlns="http://www.w3.org/2000/svg" class="avatar" fill="currentColor"
              class="bi bi-person-circle" viewBox="0 0 16 16" >
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
        <path fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
      </svg>
      <%= get_author(@article.user_id).name%>
      <div class="right_floating_box">
        <% if following?(@article.user_id) %>
          <%status = 'Unfollow' %>
          <%btn_class = 'btn btn-danger' %>
        <% else %>
          <%status = 'Follow' %>
          <%btn_class = 'btn btn-primary' %>
        <% end %>
        <%= button_to status, {action: 'toggle_follow'}, params: { current_user: @current_user, author: @article.user_id }, data: {confirm: 'Are you sure?'}, class: btn_class %>
        <div class="form-check form-switch">
        </div>
      </div>
    </div>
    <div class="card-body">
      <h4 class="card-title"><%= @article.title %></h4>
      <p class="card-text"><%= @article.body %></p>
      <% unless @visitor %>
        <div class="row">
          <div class="col col-lg-1">
            <%= button_to 'Edit', edit_article_path(@article), method: :get, class: 'btn btn-warning' %>
          </div>
          <div class="col col-lg-1">
            <%= button_to 'Destroy', article_path(@article), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <h2>Comments</h2>
  <div class="row">
    <%= render @article.comments %>
  </div>
  <h2>Add a comment:</h2>
  <% if following?(@article.user_id) %>
    <div id="comment-section">
      <%= render 'comments/form' %>
    </div>
  <% else  %>
    <div class="alert alert-dismissible alert-warning" id="follow-first">
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      <h4 class="alert-heading">Warning!</h4>
      <p class="mb-0"><strong>Want to leave a comment? </strong>You must follow the author first!</p>
    </div>
  <% end  %>
</div>

app/views/articles/user_index.html.erb
<div class="row">
  <h1>Articles</h1>
</div>
<br>
<h1 class="text-primary">Hi! <strong><%= @current_user.name %></strong> you have <em><%= @current_user.articles.public_count %> </em> articles and counting!</h1>
<br>
<div class="row">
  <% @articles.each do |a|%>
    <div class="col col-lg-4">
      <div class="card border-primary mb-3 mw-20rem" >
        <div class="card-header">
          <svg xmlns="http://www.w3.org/2000/svg" class="avatar" fill="currentColor"
              class="bi bi-person-circle" viewBox="0 0 16 16" >
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
            <path fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
          </svg>
          <%= get_author(a.user_id).name%>
          <% case a.status %>
          <% when 'public' %>
          <span class="badge bg-warning">Public</span>
          <% when 'private' %>
          <span class="badge bg-dark" >Private</span>
          <% when 'archived' %>
          <span class="badge bg-danger">Archived</span>
        <% end%>
      </div>
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to a.title, a %>
        </h4>
        <p class="card-text"><%= a.body %></p>
      </div>
    </div>
  </div>
<%end%>
</div>

app/views/comments/_comment.html.erb
<div class="col col-lg-4">
  <div class="card border-secondary mb-3 mw-20rem">
    <div class="card-header">
      <svg xmlns="http://www.w3.org/2000/svg" class="avatar" fill="currentColor"
              class="bi bi-person-circle" viewBox="0 0 16 16" >
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
        <path fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
      </svg>
      <%= comment.commenter %>
    </div>
    <div class="card-body">
      <h4 class="card-title"><strong>Comment:</strong></h4>
      <p class="card-text"><%= comment.body %></p>
      <% if (comment.user_id == current_user.id) or (@article.user_id == current_user.id)  %>
        <p>
          <%= button_to 'Destroy Comment', [ comment.article, comment ],
                method: :delete,
                data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %>
    <svg xmlns="http://www.w3.org/2000/svg" class="avatar" fill="currentColor"
              class="bi bi-person-circle" viewBox="0 0 16 16" >
      <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
      <path fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
    </svg>
    <%= form.text_field :commenter, class:'form-control', value: current_user.name, readonly: true%>
    <%= form.hidden_field :user_id, value: current_user.id  %>
  </p>
  <p>
    <%= form.label :body %>
    <%= form.text_area :body, class:'form-control' %>
  </p>
  <p>
    <%= form.label :status %> <br>
    <%= form.select :status, ['public', 'private', 'archived'], {}, {selected:'public', class: 'form-select'} %>
  </p>
  <p>
    <%= form.submit class: 'btn btn-success' %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Roa's Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
      aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <% if logged_in? %>
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to 'Articles', articles_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Articles', user_articles_path, class: 'nav-link active' %>
          </li>
          <li>
            <%= link_to 'New Article', new_article_path, class: 'nav-link' %>
          </li>
        </ul>
        <ul class="nav navbar-right ">
          <li>
            <svg xmlns="http://www.w3.org/2000/svg" width="40px" height="40px" fill="currentColor"
              class="bi bi-person-circle" viewBox="0 0 16 16" >
              <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
              <path fill-rule="evenodd"
                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
            </svg>
            <%= @current_user.name %>
          </li>
          &nbsp;&nbsp;
          <li>
            <%= button_to "Log out" , logout_path, class: "btn btn-light" , method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-right ">
          <li>
            <%= button_to "Log in" , login_path, method: :get,class: "btn btn-light" %>
          </li>
          <li>
            <%= button_to "Sign up" , signup_path, method: :get, class: "btn btn-secondary" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type%>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li class='text-danger'><%= msg %>    </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1 class="text-center">Sign up</h1>

<div clas="row">
  <div class="col-md-4 offset-4">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"  %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control"%>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="offset-4 col-md-4">
    <h3 class='text-center'>
      <%= @user.name %>
    </h3>
    <h3 class='text-center'>
      <%= @user.email %>
    </h3>
  </div>
</div>